name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Add components
      run: rustup component add rustfmt clippy

    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --fix -- --deny warnings

    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - run: cargo check

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2
    - run : cargo build --verbose
